name: 'Deploy to main'
on:
  push:
    branches:
      - develop
      #- main

permissions:
  contents: read

jobs:
  deploy_terraform:
    name: Deploy project bootstrap
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}

#      - name: Terraform plan
#        run: terraform plan
#        env:
#          GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}
#
#      - name: Terraform apply
#        run: terraform apply -auto-approve
#        env:
#          GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}
